// GENERATED by @ds/tokens — do not edit.

/** Semantic "color" tokens (literal union). */
export type DsColorToken =
  | "color.accent.default"
  | "color.accent.emphasis"
  | "color.accent.muted"
  | "color.border.default"
  | "color.border.focus"
  | "color.border.muted"
  | "color.border.strong"
  | "color.status.danger.border"
  | "color.status.danger.default"
  | "color.status.danger.emphasis"
  | "color.status.danger.surface"
  | "color.status.danger.text"
  | "color.status.info.border"
  | "color.status.info.default"
  | "color.status.info.emphasis"
  | "color.status.info.surface"
  | "color.status.info.text"
  | "color.status.success.border"
  | "color.status.success.default"
  | "color.status.success.emphasis"
  | "color.status.success.surface"
  | "color.status.success.text"
  | "color.status.warning.border"
  | "color.status.warning.default"
  | "color.status.warning.emphasis"
  | "color.status.warning.surface"
  | "color.status.warning.text"
  | "color.surface.default"
  | "color.surface.inverse"
  | "color.surface.overlay"
  | "color.surface.raised"
  | "color.surface.sunken"
  | "color.surface.sunken-hover"
  | "color.text.inverse"
  | "color.text.link"
  | "color.text.muted"
  | "color.text.on-accent"
  | "color.text.primary"
  | "color.text.secondary";

/** Semantic "font" tokens (literal union). */
export type DsFontToken =
  | "font.family.mono"
  | "font.family.sans";

/** Semantic "text" tokens (literal union). */
export type DsTextToken =
  | "text.leading.loose"
  | "text.leading.normal"
  | "text.leading.tight"
  | "text.size.2xl"
  | "text.size.3xl"
  | "text.size.lg"
  | "text.size.md"
  | "text.size.sm"
  | "text.size.xl"
  | "text.size.xs"
  | "text.weight.bold"
  | "text.weight.medium"
  | "text.weight.regular"
  | "text.weight.semibold";

/** Semantic "space" tokens (literal union). */
export type DsSpaceToken =
  | "space.0"
  | "space.1"
  | "space.10"
  | "space.2"
  | "space.3"
  | "space.4"
  | "space.5"
  | "space.6"
  | "space.7"
  | "space.8"
  | "space.9"
  | "space.gap.lg"
  | "space.gap.md"
  | "space.gap.sm"
  | "space.inset.lg"
  | "space.inset.md"
  | "space.inset.sm";

/** Semantic "radius" tokens (literal union). */
export type DsRadiusToken =
  | "radius.full"
  | "radius.lg"
  | "radius.md"
  | "radius.sm";

/** Semantic "border" tokens (literal union). */
export type DsBorderToken =
  | "border.width.1"
  | "border.width.2";

/** Semantic "shadow" tokens (literal union). */
export type DsShadowToken =
  | "shadow.focus-ring"
  | "shadow.overlay"
  | "shadow.raised";

/** Semantic "motion" tokens (literal union). */
export type DsMotionToken =
  | "motion.duration.fast"
  | "motion.duration.normal"
  | "motion.duration.slow"
  | "motion.easing.enter"
  | "motion.easing.exit"
  | "motion.easing.standard";

/** Semantic "z" tokens (literal union). */
export type DsZToken =
  | "z.dropdown"
  | "z.overlay"
  | "z.sticky"
  | "z.toast"
  | "z.tooltip";

/** Semantic "size" tokens (literal union). */
export type DsSizeToken =
  | "size.control.lg"
  | "size.control.md"
  | "size.control.sm"
  | "size.icon.lg"
  | "size.icon.md"
  | "size.icon.sm";

/** Component-tier tokens (literal union). */
export type DsComponentToken =
  | "alert.border-width"
  | "alert.border.danger"
  | "alert.border.info"
  | "alert.border.success"
  | "alert.border.warning"
  | "alert.dismiss.surface.hover"
  | "alert.dismiss.surface.pressed"
  | "alert.gap"
  | "alert.icon.danger"
  | "alert.icon.info"
  | "alert.icon.success"
  | "alert.icon.warning"
  | "alert.padding"
  | "alert.radius"
  | "alert.surface.danger"
  | "alert.surface.info"
  | "alert.surface.success"
  | "alert.surface.warning"
  | "alert.text.danger"
  | "alert.text.info"
  | "alert.text.success"
  | "alert.text.warning"
  | "badge.font-size"
  | "badge.font-weight"
  | "badge.padding-x"
  | "badge.padding-y"
  | "badge.radius"
  | "badge.surface.danger"
  | "badge.surface.info"
  | "badge.surface.neutral"
  | "badge.surface.success"
  | "badge.surface.warning"
  | "badge.text.danger"
  | "badge.text.info"
  | "badge.text.neutral"
  | "badge.text.success"
  | "badge.text.warning"
  | "button.border.secondary"
  | "button.font-weight"
  | "button.gap"
  | "button.height.lg"
  | "button.height.md"
  | "button.height.sm"
  | "button.padding-x.lg"
  | "button.padding-x.md"
  | "button.padding-x.sm"
  | "button.radius"
  | "button.surface.danger.default"
  | "button.surface.danger.hover"
  | "button.surface.ghost.hover"
  | "button.surface.primary.default"
  | "button.surface.primary.hover"
  | "button.surface.secondary.default"
  | "button.surface.secondary.hover"
  | "button.text.danger"
  | "button.text.ghost"
  | "button.text.primary"
  | "button.text.secondary"
  | "card.border"
  | "card.gap"
  | "card.padding"
  | "card.radius"
  | "card.shadow"
  | "card.surface"
  | "checkbox.border.default"
  | "checkbox.border.invalid"
  | "checkbox.mark"
  | "checkbox.radius"
  | "checkbox.size"
  | "checkbox.surface.default"
  | "checkbox.surface.selected"
  | "checkbox.surface.selected-hover"
  | "dialog.backdrop"
  | "dialog.backdrop-opacity"
  | "dialog.gap"
  | "dialog.padding"
  | "dialog.radius"
  | "dialog.shadow"
  | "dialog.surface"
  | "dialog.width.lg"
  | "dialog.width.md"
  | "dialog.width.sm"
  | "dialog.z"
  | "field.border.default"
  | "field.border.disabled"
  | "field.border.focus"
  | "field.border.hover"
  | "field.border.invalid"
  | "field.description-text"
  | "field.error-text"
  | "field.gap"
  | "field.height"
  | "field.label-text"
  | "field.padding-x"
  | "field.padding-y"
  | "field.placeholder"
  | "field.radius"
  | "field.surface"
  | "field.surface-disabled"
  | "field.text"
  | "field.text-disabled"
  | "radio.dot"
  | "radio.gap"
  | "radio.size"
  | "radio.surface.selected"
  | "radio.surface.selected-hover"
  | "switch.surface.off"
  | "switch.surface.on"
  | "switch.surface.on-hover"
  | "switch.thumb"
  | "switch.thumb-size"
  | "switch.track-height"
  | "switch.track-width"
  | "tabs.border"
  | "tabs.font-weight"
  | "tabs.gap"
  | "tabs.indicator.selected"
  | "tabs.padding-x"
  | "tabs.padding-y"
  | "tabs.text.default"
  | "tabs.text.hover"
  | "tabs.text.selected"
  | "tooltip.font-size"
  | "tooltip.max-width"
  | "tooltip.padding-x"
  | "tooltip.padding-y"
  | "tooltip.radius"
  | "tooltip.shadow"
  | "tooltip.surface"
  | "tooltip.text"
  | "tooltip.z";

export type DsSemanticToken =
  | DsColorToken
  | DsFontToken
  | DsTextToken
  | DsSpaceToken
  | DsRadiusToken
  | DsBorderToken
  | DsShadowToken
  | DsMotionToken
  | DsZToken
  | DsSizeToken;

export type DsToken = DsSemanticToken | DsComponentToken;

export interface DsTokenInfo {
  readonly name: DsToken;
  readonly cssVar: `--ds-${string}`;
  readonly tier: "semantic" | "component";
  readonly type: string;
  readonly description: string;
  readonly value: string | number;
}

/** Every public token, keyed by DTCG path. The closed-world map. */
export declare const tokens: Readonly<Record<DsToken, DsTokenInfo>>;

/** All public token names, sorted (semantic tier first, then component). */
export declare const tokenNames: readonly DsToken[];

/** Returns `var(--ds-...)` for a known token; throws on anything else. */
export declare function cssVarRef(name: DsToken): string;
