/** RETROFIT.md — the human report: what was detected, per-adapter confidence,
 *  what needs human confirmation, and next steps. Deterministic (no clocks). */

import type { RetrofitResult } from './types.js';

function count<T>(arr: T[] | null | undefined): number {
  return arr === null || arr === undefined ? 0 : arr.length;
}

export function renderRetrofitMd(r: RetrofitResult): string {
  const lines: string[] = [];
  const push = (s = ''): void => {
    lines.push(s);
  };

  push('# Retrofit report');
  push();
  push(`Target: \`${r.componentsIndex?.package ?? r.repoRoot}\` · brand name: \`${r.brandName}\``);
  push();
  push('Generated by `@ds/retrofit` — deterministic, credential-free, no LLM. Their design system in, the AI layer out, without rewriting their components.');
  push();

  if (!r.detected) {
    push('## Nothing detected');
    push();
    push('No adapter fired on this repository. The scan looked for:');
    push();
    push('- CSS custom properties: any `--*` declaration in `**/*.css` (node_modules/dist ignored)');
    push('- Tailwind: `tailwind.config.{js,cjs,mjs,ts}` with a literal `theme` object');
    push('- DTCG / Style Dictionary: `.json` files containing `$value` token trees');
    push('- React components: `package.json` types/main entry or `src/**/*.{tsx,jsx,ts,js}` parseable by react-docgen-typescript');
    push();
    push('Next steps: point `ds-retrofit` at the directory that contains the design-system source (it may live in a sub-package), or pass `--components <glob>` at the component sources directly.');
    push();
    return lines.join('\n');
  }

  // ------------------------------------------------------------- summary
  push('## Detection summary');
  push();
  push('| Adapter | Detected | Output | Confidence |');
  push('| --- | --- | --- | --- |');
  const cssTokenCount = count(r.tokensIndex?.tokens.filter((t) => t.provenance.adapter === 'css-custom-properties') ?? []);
  const twTokenCount = count(r.tokensIndex?.tokens.filter((t) => t.provenance.adapter === 'tailwind') ?? []);
  const dtcgTokenCount = count(r.tokensIndex?.tokens.filter((t) => t.provenance.adapter === 'dtcg') ?? []);
  push(
    `| CSS custom properties | ${r.detection.css.length} stylesheet(s) | ${cssTokenCount} token(s) | HIGH — values shipped in CSS, resolved from declarations |`,
  );
  push(
    `| Tailwind config | ${r.detection.tailwind ?? '—'} | ${twTokenCount} token(s), ${r.tailwindMappings.length} mapping row(s) | MEDIUM — static literal extraction only (config never executed); vars are PROPOSALS |`,
  );
  push(
    `| DTCG / Style Dictionary | ${r.detection.dtcg.length} file(s) | ${dtcgTokenCount} token(s) | HIGH — direct conversion of declared source of truth |`,
  );
  push(
    `| React components (docgen) | entry: ${r.detection.componentEntry ?? 'discovered by scan'} | ${count(r.componentsIndex?.components)} component(s) | per component, see below |`,
  );
  push();

  // -------------------------------------------------------------- tokens
  push('## Tokens');
  push();
  push(`\`registries/tokens-index.json\` — ${r.tokensIndex?.count ?? 0} token(s), tier \`semantic\` as a best-effort default. Names were normalized from three-way inconsistent spellings (camel/snake/kebab) to dot paths; \`cssVar\` keeps the ORIGINAL spelling so the closed-world check validates real usage. Every entry carries \`provenance\` (adapter, source file:line, original spelling).`);
  push();
  if (r.unresolvedVars.length > 0) {
    push(`Unresolved \`var()\`/alias chains (${r.unresolvedVars.length}): ${r.unresolvedVars.map((v) => `\`${v}\``).join(', ')} — values kept raw; resolve manually.`);
    push();
  }
  if (r.tailwindMappings.length > 0) {
    push('### Proposed Tailwind mapping (also in `tailwind-mapping.json`)');
    push();
    push('| theme path | proposed var | value | matches existing var |');
    push('| --- | --- | --- | --- |');
    for (const m of r.tailwindMappings) {
      push(`| \`${m.themePath}\` | \`${m.proposedVar}\` | \`${m.value}\` | ${m.matchesExistingVar ? `\`${m.matchesExistingVar}\`` : '—'} |`);
    }
    push();
    push('Rows with a match duplicate an already-shipped custom property — adopt the existing var instead of minting the proposal.');
    push();
  }
  if (r.skippedTailwindPaths.length > 0) {
    push(`Tailwind entries skipped as non-literal (functions/spreads — the config is never executed): ${r.skippedTailwindPaths.map((p) => `\`${p}\``).join(', ')}.`);
    push();
  }

  // ------------------------------------------------------------ contrast
  push('## Contrast (best-effort)');
  push();
  const cr = r.contrastReport;
  if (cr !== null) {
    push(`\`registries/contrast-report.json\` — ${cr.pairs.length} inferred pair(s), **${cr.failures} failure(s)** at ${cr.threshold}:1, ${cr.unaudited.length} color token(s) unaudited.`);
    push();
    push('Pair inference is heuristic (documented in the report `$description`): stem pairs (`x` on `x.bg`) plus text-classified × surface-classified cross pairs. The `unaudited` list is an audit backlog, not a pass.');
    push();
    const failures = cr.pairs.filter((p) => !p.pass);
    if (failures.length > 0) {
      push('| failing pair | ratio | required |');
      push('| --- | --- | --- |');
      for (const p of failures) push(`| \`${p.id}\` | ${p.ratio} | ${p.required} |`);
      push();
    }
  }

  // ---------------------------------------------------------- components
  push('## Components');
  push();
  push(`\`registries/components-index.json\` — closed world: any component not listed does not exist. Props extracted from the library's own types by react-docgen-typescript; \`racBase\`/\`tokenPrefix\` are null (no react-aria contract, no component-tier tokens); \`example\` values are synthesized minimal usage, not ground truth.`);
  push();
  push('| Component | Source | Props | Typing confidence | Story file |');
  push('| --- | --- | --- | --- | --- |');
  for (const c of r.componentConfidence) {
    const entry = r.componentsIndex?.components.find((x) => x.name === c.name);
    push(
      `| ${c.name} | \`${c.file}\` | ${c.props} | ${c.typing === 'typed' ? 'HIGH (typed)' : 'LOW (untyped — no prop contract extractable)'} | ${entry?.storyFile !== undefined ? `\`${entry.storyFile}\`` : '—'} |`,
    );
  }
  push();

  // ------------------------------------------------------ hardcoded sins
  if (r.hardcoded.length > 0) {
    push('## Hard-coded color literals found (tokenization backlog)');
    push();
    push('| file:line | property | literal |');
    push('| --- | --- | --- |');
    for (const h of r.hardcoded) push(`| \`${h.source}:${h.line}\` | \`${h.property}\` | \`${h.literal}\` |`);
    push();
  }

  // -------------------------------------------------------- context layer
  push('## Emitted AI layer');
  push();
  if (r.contextStatus === 'emitted') {
    push(`\`context/\` — ${r.contextFiles} file(s) compiled by \`@ds/context\` from the synthesized registries: the llms.txt family, per-component markdown docs, skills, AGENTS.md/CLAUDE.md routers, editor rules (Cursor/Copilot/Claude Code/v0), the ds-auditor agent, extension-points.json, and registry byte-copies with a hashed manifest.`);
  } else if (r.contextStatus === 'failed') {
    push(`Context compilation FAILED — registries and this report were still emitted. Error: \`${r.contextError ?? 'unknown'}\``);
  } else {
    push('Context compilation skipped (`--no-context`).');
  }
  push();
  push('`gauntlet.config.json` — starter enforcement config. Enforceable today: the closed-world token check (G1) and component check (G5) against the synthesized registries — after retrofit, an agent can no longer fabricate this system\'s tokens or components. Advisory/off rules carry reasons.');
  push();

  // ------------------------------------------------- human confirmation
  push('## Needs human confirmation');
  push();
  push('1. **Token tiers** — every token is tier `semantic` as a best-effort default; reclassify raw palette scales (and component-specific vars) after review.');
  push('2. **Tailwind proposals** — proposed `--tw-*` vars do not exist in shipped CSS; adopt, rename, or map them to existing vars per the mapping table before enforcing them.');
  push('3. **Contrast pairings** — the heuristic pairs are inferred, not designed; confirm intended text/surface combinations and audit the `unaudited` backlog.');
  push('4. **Untyped components** — components listed with LOW confidence have no extractable prop contract; add types (or a docgen annotation pass) to close their prop surface.');
  push('5. **Duplicate values** — near-identical values across naming eras (see mapping table matches) are consolidation candidates.');
  push();

  // ------------------------------------------------------------ next steps
  push('## Next steps');
  push();
  push('1. Ship `context/` artifacts to the repos where agents generate UI (AGENTS.md/CLAUDE.md at the root, editor rules per channel).');
  push('2. Wire `gauntlet.config.json` enforce-rules into CI (closed-world token + component checks are deterministic and safe to gate merges today).');
  push('3. Work the confirmation list above, then re-run `ds-retrofit` — the pipeline is idempotent and deterministic.');
  push('4. Graduate: promote confirmed tokens into a DTCG source and let the full AIR-DS pipeline (tokens build, contrast gate, context compiler) run from source instead of from scans.');
  push();

  if (r.warnings.length > 0) {
    push('## Warnings');
    push();
    for (const w of r.warnings) push(`- ${w}`);
    push();
  }

  push('## Limitations (honest list)');
  push();
  push('- Tailwind extraction is static: functions, spreads, `require()`d presets and plugin-contributed theme values are skipped (listed above when hit).');
  push('- Contrast pairs are inferred from token NAMES, not from rendered usage; the report is an audit starting point, not WCAG evidence.');
  push('- `tier: "semantic"` is asserted, not known — raw palette scales are registered but not reclassified.');
  push('- Untyped (plain JS) components register with an empty prop list — the closed world covers the component NAME, not its props.');
  push('- Story-file detection is co-location-based (`<Name>.stories.*` next to the source); other story layouts are not found.');
  push('- The context bundle\'s prose skills/rules were designed for AIR-DS conventions — e.g. `llms.txt` says "Import everything from `@ds/react`" and references `--ds-*` naming, while THIS system imports from its own package and ships its own var names. The registries, closed-world data, and per-component docs are target-true; review the rule prose before shipping to agents (retrofit-aware prose is tracked as a @ds/context follow-up).');
  push();

  return lines.join('\n');
}
