#!/usr/bin/env node
/**
 * Metrics reporter — renders metrics/history.jsonl into metrics/README.md:
 * a latest-snapshot section plus a per-release (per git sha) trend table.
 *
 *   pnpm --filter @ds/validate run metrics:report [-- --root <dir>] [--out <file>]
 *
 * Pure filesystem in, filesystem out. No network, no credentials (ADR-005:
 * everything in the tracking path is deterministic).
 */

import { writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { findRepoRoot } from '../registry.ts';
import { historyPath, readHistory, type MetricsLine } from './record.ts';

interface ShaGroup {
  sha: string;
  ts: string;
  gauntlet?: MetricsLine['gauntlet'];
  evals?: MetricsLine['evals'];
  benchmark?: MetricsLine['benchmark'];
  storiesAxe?: MetricsLine['storiesAxe'];
  fabrications: number;
  counts: MetricsLine['registry_counts'];
}

/** Merge history lines per git sha, newest line per section wins. */
export function groupBySha(lines: MetricsLine[]): ShaGroup[] {
  const groups = new Map<string, ShaGroup>();
  const order: string[] = [];
  for (const line of lines) {
    let g = groups.get(line.git_sha);
    if (!g) {
      g = { sha: line.git_sha, ts: line.ts, fabrications: 0, counts: line.registry_counts };
      groups.set(line.git_sha, g);
      order.push(line.git_sha);
    }
    g.ts = line.ts;
    g.counts = line.registry_counts;
    if (line.gauntlet) g.gauntlet = line.gauntlet;
    if (line.evals) g.evals = line.evals;
    if (line.benchmark) g.benchmark = line.benchmark;
    if (line.storiesAxe) g.storiesAxe = line.storiesAxe;
    g.fabrications = Math.max(g.fabrications, line.fabrications);
  }
  return order.map((sha) => groups.get(sha) as ShaGroup);
}

const pct = (n: number): string => `${(n * 100).toFixed(1)}%`;

function benchmarkCell(b: MetricsLine['benchmark']): string {
  if (!b) return '—';
  const system = b.sources['recorded:system'] ?? b.sources['fixture:good'];
  const baseline = b.sources['baseline:raw-tailwind'];
  const sys = system ? pct(system.avgTokenCompliance) : '—';
  const base = baseline ? pct(baseline.avgTokenCompliance) : '—';
  return `${sys} vs ${base} (axe ${b.axe})`;
}

export function renderReport(lines: MetricsLine[]): string {
  const groups = groupBySha(lines);
  const out: string[] = [
    '# AIR-DS release metrics',
    '',
    'GENERATED by `pnpm --filter @ds/validate run metrics:report` from `metrics/history.jsonl` — do not edit by hand.',
    'Each gauntlet / eval / benchmark CLI run appends one line to the history; this report merges them per git sha (brief §8 success metrics).',
    '',
  ];

  if (groups.length === 0) {
    out.push('_No metrics recorded yet. Run `pnpm validate`, `pnpm --filter @ds/validate run evals`, or `pnpm --filter @ds/validate run benchmark` to append the first lines._', '');
    return out.join('\n');
  }

  const latest = groups[groups.length - 1] as ShaGroup;
  out.push('## Latest snapshot', '', `- **Commit:** \`${latest.sha}\` (${latest.ts})`);
  if (latest.gauntlet) {
    const total = Object.values(latest.gauntlet.durations).reduce((a, b) => a + b, 0);
    out.push(
      `- **Gauntlet:** ${latest.gauntlet.passed ? 'PASSED' : 'FAILED'} — ${latest.gauntlet.steps} step(s) in ${total}ms (${Object.entries(
        latest.gauntlet.durations,
      )
        .map(([k, v]) => `${k} ${v}ms`)
        .join(', ')})`,
    );
  }
  if (latest.evals) {
    out.push(
      `- **Evals:** overall ${pct(latest.evals.overall)} (${latest.evals.passed}/${latest.evals.total}), critical ${pct(latest.evals.critical)} — gates: critical 1.0, overall ≥ 0.95`,
    );
  }
  if (latest.storiesAxe) {
    const sa = latest.storiesAxe;
    out.push(
      `- **Stories axe (G6):** ${sa.gatePassed ? 'GATE PASSED' : 'GATE FAILED'} — ${sa.stories} stories, ${sa.violations} violation(s) (${sa.serious} serious, ${sa.critical} critical), ${sa.storiesWithViolations} story(ies) affected`,
    );
  }
  out.push(`- **Fabrications (G1/G5):** ${latest.fabrications} — target 0`);
  out.push(`- **Registry counts:** ${latest.counts.tokens} tokens, ${latest.counts.components} components`);
  if (latest.benchmark) {
    out.push(`- **Benchmark (${latest.benchmark.mode}, ${latest.benchmark.scenarios} scenario(s)):** token compliance ${benchmarkCell(latest.benchmark)}`);
    for (const [source, agg] of Object.entries(latest.benchmark.sources)) {
      out.push(
        `  - ${source}: compliance ${pct(agg.avgTokenCompliance)}, fabrications ${agg.fabrications}, gauntlet pass rate ${pct(agg.gauntletPassRate)}`,
      );
    }
  }
  out.push('');

  out.push(
    '## Trend (per release)',
    '',
    '| ts | sha | gauntlet | evals overall | evals critical | fabrications | tokens | components | benchmark (system vs baseline) |',
    '|---|---|---|---:|---:|---:|---:|---:|---|',
  );
  for (const g of groups) {
    out.push(
      `| ${g.ts} | \`${g.sha}\` | ${g.gauntlet ? (g.gauntlet.passed ? 'PASS' : 'FAIL') : '—'} | ${g.evals ? pct(g.evals.overall) : '—'} | ${g.evals ? pct(g.evals.critical) : '—'} | ${g.fabrications} | ${g.counts.tokens} | ${g.counts.components} | ${benchmarkCell(g.benchmark)} |`,
    );
  }
  out.push('');
  return out.join('\n');
}

// CLI entry
const isMain = process.argv[1] && resolve(process.argv[1]).includes('report');
if (isMain) {
  const argv = process.argv.slice(2);
  const rootIdx = argv.indexOf('--root');
  const root = rootIdx !== -1 ? resolve(argv[rootIdx + 1] ?? '.') : findRepoRoot(process.cwd());
  const outIdx = argv.indexOf('--out');
  const outPath = outIdx !== -1 ? resolve(argv[outIdx + 1] ?? '.') : join(root, 'metrics', 'README.md');

  const lines = readHistory(historyPath(root));
  writeFileSync(outPath, renderReport(lines), 'utf8');
  console.log(`metrics report: ${lines.length} history line(s) -> ${outPath}`);
}
