#!/usr/bin/env node
/**
 * release-version — lean, hand-rolled version bump + changelog generation.
 * (Chosen over changesets: zero extra deps, no daemon, plays nicely with the
 * pnpm workspace, and keeps the release path 100% credential-free.)
 *
 *   node scripts/release-version.mjs <major|minor|patch|x.y.z> [--dry-run] [--now <iso>]
 *
 * What it does (locally, no network):
 *   1. bumps `version` in every publishable package.json (packages/* +
 *      tooling/*; `workspace:*` cross-refs need no rewrite — pnpm pack
 *      resolves them to the packed versions)
 *   2. prepends a changelog section to CHANGELOG.md generated from
 *      `git log` since the previous release tag (or full history)
 *   3. prints the follow-up commands (commit, tag, release-pack)
 *
 * It never commits, never tags, never publishes — a release engineer reviews
 * the diff first (mirrors customer-builds/<name>/publish-plan.json policy).
 */

import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const PUBLISHABLE = [
  'packages/tokens',
  'packages/react',
  'packages/mcp',
  'packages/context',
  'tooling/validate',
  'tooling/ingest',
];

function git(args) {
  try {
    return execFileSync('git', args, {
      cwd: ROOT,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
  } catch {
    return '';
  }
}

function bump(version, kind) {
  const m = /^(\d+)\.(\d+)\.(\d+)/.exec(version);
  if (!m) throw new Error(`unparseable version: ${version}`);
  const [major, minor, patch] = [Number(m[1]), Number(m[2]), Number(m[3])];
  if (kind === 'major') return `${major + 1}.0.0`;
  if (kind === 'minor') return `${major}.${minor + 1}.0`;
  if (kind === 'patch') return `${major}.${minor}.${patch + 1}`;
  if (/^\d+\.\d+\.\d+$/.test(kind)) return kind;
  throw new Error(`usage: release-version <major|minor|patch|x.y.z> [--dry-run]`);
}

const argv = process.argv.slice(2);
const kind = argv[0];
const dryRun = argv.includes('--dry-run');
const nowIdx = argv.indexOf('--now');
const now = nowIdx !== -1 ? argv[nowIdx + 1] : new Date().toISOString().slice(0, 10);
if (!kind) {
  console.error('usage: node scripts/release-version.mjs <major|minor|patch|x.y.z> [--dry-run] [--now <date>]');
  process.exit(2);
}

const current = JSON.parse(readFileSync(join(ROOT, 'packages/tokens/package.json'), 'utf8')).version;
const next = bump(current, kind);

console.log(`release-version: ${current} -> ${next}${dryRun ? ' (dry run)' : ''}`);

// 1. Bump every publishable package.
for (const pkg of PUBLISHABLE) {
  const path = join(ROOT, pkg, 'package.json');
  const json = JSON.parse(readFileSync(path, 'utf8'));
  console.log(`  ${json.name}: ${json.version} -> ${next}`);
  if (!dryRun) {
    const raw = readFileSync(path, 'utf8');
    writeFileSync(path, raw.replace(`"version": "${json.version}"`, `"version": "${next}"`), 'utf8');
  }
}

// 2. Changelog from git history since the last release tag.
const lastTag = git(['describe', '--tags', '--abbrev=0', '--match', 'v*']);
const range = lastTag ? `${lastTag}..HEAD` : 'HEAD';
const log = git(['log', '--no-merges', '--pretty=format:- %s (%h)', range]);
const section = [
  `## v${next} — ${now}`,
  '',
  lastTag ? `Changes since ${lastTag}:` : 'Initial tracked release.',
  '',
  log || '- (no commits found)',
  '',
  '',
].join('\n');

const changelogPath = join(ROOT, 'CHANGELOG.md');
const header = '# Changelog\n\nGenerated by `scripts/release-version.mjs` from git history. Newest first.\n\n';
const existing = existsSync(changelogPath)
  ? readFileSync(changelogPath, 'utf8').replace(header, '')
  : '';
if (!dryRun) writeFileSync(changelogPath, header + section + existing, 'utf8');
console.log(`  CHANGELOG.md: prepended v${next} section (${log ? log.split('\n').length : 0} commit(s) since ${lastTag || 'repo start'})`);

// 3. Follow-ups (manual on purpose).
console.log(`
Next steps (review the diff first — nothing is committed for you):
  git add -A && git commit -m "release: v${next}"
  git tag v${next}
  bash scripts/release-pack.sh        # tarballs + version-stamped registry bundle
  # publish: .github/workflows/release.yml (disabled step; client provides NPM_TOKEN)
`);
