import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { isAbsolute, join, relative, resolve } from 'node:path';
import type {
  CompilerInputs,
  ComponentsIndex,
  ContrastReport,
  IconEntry,
  IconsMetadata,
  PatternEntry,
  PatternsIndex,
  TokensIndex,
} from './types.ts';
import { parseNegativeRules } from './rules.ts';

const REG_TOKENS = 'registries/tokens-index.json';
const REG_COMPONENTS = 'registries/components-index.json';
const REG_CONTRAST = 'registries/contrast-report.json';
const REG_ICONS = 'registries/icons-metadata.json';
const REG_PATTERNS = 'registries/patterns-index.json';
const NEGATIVE_RULES = 'docs/specs/negative-rules.md';
const CONTRIBUTING = 'packages/react/CONTRIBUTING-COMPONENT.md';
const AUDITOR_TEMPLATE = '.claude/agents/ds-auditor.md';
const COMPONENTS_SRC = 'packages/react/src/components';

export interface LoadOptions {
  /** Directory containing the registry JSON files. Default: <repoRoot>/registries. */
  registriesDir?: string;
  /** Path to the brand file. Default: <repoRoot>/brands/<brand>.json. */
  brandPath?: string;
}

/** Repo-relative when inside the repo, absolute otherwise (manifest display path). */
function displayPath(repoRoot: string, abs: string): string {
  const rel = relative(repoRoot, abs);
  return rel === '' || rel.startsWith('..') || isAbsolute(rel) ? abs : rel.split('\\').join('/');
}

/**
 * Read every compiler input FRESH from disk (registries may be regenerated by
 * other pipeline stages between runs — never cache values into source).
 *
 * Optional registries (icons-metadata.json, patterns-index.json) and optional
 * components-index enrichment fields (racProps / tokenPrefix / storyFile) are
 * consumed when present and degrade to a manifest warning when absent — the
 * build stays green in both registry states.
 */
export function loadInputs(repoRoot: string, brand: string, options: LoadOptions = {}): CompilerInputs {
  const registriesDir = resolve(options.registriesDir ?? join(repoRoot, 'registries'));
  const brandFile = resolve(options.brandPath ?? join(repoRoot, 'brands', `${brand}.json`));

  const rawInputs = new Map<string, Buffer>();
  const inputPaths = new Map<string, string>();
  /** Read a file, keyed under a STABLE logical path (hashing + bundle copies). */
  const readAs = (logical: string, abs: string): Buffer => {
    const buf = readFileSync(abs);
    rawInputs.set(logical, buf);
    inputPaths.set(logical, displayPath(repoRoot, abs));
    return buf;
  };
  const read = (rel: string): Buffer => readAs(rel, join(repoRoot, rel));
  const readRegistry = (logical: string): Buffer =>
    readAs(logical, join(registriesDir, logical.slice('registries/'.length)));

  const warnings: string[] = [];

  const tokensIndex = JSON.parse(readRegistry(REG_TOKENS).toString('utf8')) as TokensIndex;
  const componentsIndex = JSON.parse(readRegistry(REG_COMPONENTS).toString('utf8')) as ComponentsIndex;
  const contrastReport = JSON.parse(readRegistry(REG_CONTRAST).toString('utf8')) as ContrastReport;

  // Optional registries: consume when present, warn (manifest) when absent.
  let iconsMetadata: IconsMetadata | null = null;
  let patternsIndex: PatternsIndex | null = null;
  if (existsSync(join(registriesDir, 'icons-metadata.json'))) {
    iconsMetadata = normalizeIcons(JSON.parse(readRegistry(REG_ICONS).toString('utf8')));
  } else {
    warnings.push(
      `optional registry ${REG_ICONS} not found in ${displayPath(repoRoot, registriesDir)} — icon surfaces omitted from this bundle.`,
    );
  }
  if (existsSync(join(registriesDir, 'patterns-index.json'))) {
    patternsIndex = normalizePatterns(JSON.parse(readRegistry(REG_PATTERNS).toString('utf8')));
  } else {
    warnings.push(
      `optional registry ${REG_PATTERNS} not found in ${displayPath(repoRoot, registriesDir)} — pattern surfaces omitted from this bundle.`,
    );
  }

  // Optional components-index enrichment fields.
  const missingEnrichment = (['racProps', 'tokenPrefix', 'storyFile'] as const).filter(
    (field) => !componentsIndex.components.some((c) => c[field] !== undefined),
  );
  if (missingEnrichment.length > 0) {
    warnings.push(
      `components-index.json entries carry no ${missingEnrichment.join('/')} field(s) (older registry generation) — related surfacing omitted.`,
    );
  }

  const brandDisplay = displayPath(repoRoot, brandFile);
  readAs(brandDisplay.startsWith('brands/') ? brandDisplay : `brands/${brand}.json`, brandFile); // hashed as an input; resolved values come from the registry

  if (tokensIndex.brand !== brandDisplay) {
    warnings.push(
      `tokens-index.json was built against "${tokensIndex.brand}" but the brand input resolves to "${brandDisplay}". ` +
        `Resolved token values reflect the registry's brand. The ingest pipeline must sequence ` +
        `tokens-build (--brand ${brand}) before context-build.`,
    );
  }
  if (contrastReport.brand !== tokensIndex.brand) {
    warnings.push(
      `contrast-report.json brand ("${contrastReport.brand}") does not match tokens-index.json brand ("${tokensIndex.brand}").`,
    );
  }
  if (tokensIndex.count !== tokensIndex.tokens.length) {
    warnings.push(
      `tokens-index.json declares count=${tokensIndex.count} but contains ${tokensIndex.tokens.length} tokens.`,
    );
  }

  const ruleCatalog = parseNegativeRules(read(NEGATIVE_RULES).toString('utf8'));
  const contributingMd = read(CONTRIBUTING).toString('utf8');
  const auditorTemplate = read(AUDITOR_TEMPLATE).toString('utf8');

  // Stories are contract artifacts (CLAUDE.md rule 8) — ground-truth usage.
  const storyFilesByExport = new Map<string, string[]>();
  const storyContents = new Map<string, string>();
  const dirs = readdirSync(join(repoRoot, COMPONENTS_SRC), { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();
  for (const dir of dirs) {
    const rel = `${COMPONENTS_SRC}/${dir}/${dir}.stories.tsx`;
    try {
      storyContents.set(rel, read(rel).toString('utf8'));
    } catch {
      warnings.push(`missing story file for component directory ${dir} (${rel})`);
    }
  }
  for (const comp of componentsIndex.components) {
    // A story exercises a component if it renders it as JSX (<Name …>) or
    // registers it as the CSF meta component (component: Name).
    const usage = new RegExp(`<${comp.name}[\\s/>]|component:\\s*${comp.name}\\b`);
    const files = [...storyContents.keys()].filter((p) => usage.test(storyContents.get(p) as string));
    // Registry-declared storyFile (optional enrichment) joins the ground truth.
    if (comp.storyFile !== undefined && !files.includes(comp.storyFile)) files.push(comp.storyFile);
    files.sort();
    storyFilesByExport.set(comp.name, files);
    if (files.length === 0) {
      warnings.push(`registry component ${comp.name} is not used in any story file (ground-truth gap)`);
    }
  }

  return {
    brand,
    tokensIndex,
    componentsIndex,
    contrastReport,
    iconsMetadata,
    patternsIndex,
    ruleCatalog,
    contributingMd,
    auditorTemplate,
    storyFilesByExport,
    rawInputs,
    inputPaths,
    warnings,
  };
}

/* ------------------------------------------- optional-registry normalizers */

/** Tolerate `{ icons: [...] }` or a bare array; string entries become names. */
function normalizeIcons(parsed: unknown): IconsMetadata {
  const obj = (Array.isArray(parsed) ? { icons: parsed } : (parsed ?? {})) as Record<string, unknown>;
  const rawIcons = Array.isArray(obj['icons']) ? (obj['icons'] as unknown[]) : [];
  const icons: IconEntry[] = [];
  for (const raw of rawIcons) {
    if (typeof raw === 'string') {
      icons.push({ name: raw });
    } else if (raw !== null && typeof raw === 'object' && typeof (raw as IconEntry).name === 'string') {
      const r = raw as Record<string, unknown>;
      icons.push({
        name: r['name'] as string,
        ...(typeof r['export'] === 'string' ? { export: r['export'] } : {}),
        ...(typeof r['description'] === 'string' ? { description: r['description'] } : {}),
        ...(Array.isArray(r['keywords']) ? { keywords: (r['keywords'] as unknown[]).map(String) } : {}),
        ...(typeof r['category'] === 'string' ? { category: r['category'] } : {}),
        ...(Array.isArray(r['sizes']) ? { sizes: (r['sizes'] as unknown[]).map(String) } : {}),
      });
    }
  }
  icons.sort((a, b) => a.name.localeCompare(b.name));
  return {
    ...(typeof obj['$description'] === 'string' ? { $description: obj['$description'] } : {}),
    icons,
  };
}

/** Tolerate `{ patterns: [...] }` or a bare array. */
function normalizePatterns(parsed: unknown): PatternsIndex {
  const obj = (Array.isArray(parsed) ? { patterns: parsed } : (parsed ?? {})) as Record<string, unknown>;
  const rawPatterns = Array.isArray(obj['patterns']) ? (obj['patterns'] as unknown[]) : [];
  const patterns: PatternEntry[] = [];
  for (const raw of rawPatterns) {
    if (raw === null || typeof raw !== 'object') continue;
    const r = raw as Record<string, unknown>;
    // The generated registry keys patterns by `id`; tolerate `name` too.
    const name = typeof r['name'] === 'string' ? r['name'] : typeof r['id'] === 'string' ? r['id'] : null;
    if (name === null) continue;
    patterns.push({
      name,
      ...(typeof r['title'] === 'string' ? { title: r['title'] } : {}),
      ...(typeof r['description'] === 'string' ? { description: r['description'] } : {}),
      ...(Array.isArray(r['components']) ? { components: (r['components'] as unknown[]).map(String) } : {}),
      ...(typeof r['storyFile'] === 'string' ? { storyFile: r['storyFile'] } : {}),
      ...(typeof r['docFile'] === 'string' ? { docFile: r['docFile'] } : {}),
      ...(Array.isArray(r['keywords'] ) ? { keywords: (r['keywords'] as unknown[]).map(String) } : {}),
    });
  }
  patterns.sort((a, b) => a.name.localeCompare(b.name));
  return {
    ...(typeof obj['$description'] === 'string' ? { $description: obj['$description'] } : {}),
    patterns,
  };
}
