import { readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import type { CompilerInputs, ComponentsIndex, ContrastReport, TokensIndex } from './types.ts';
import { parseNegativeRules } from './rules.ts';

const REG_TOKENS = 'registries/tokens-index.json';
const REG_COMPONENTS = 'registries/components-index.json';
const REG_CONTRAST = 'registries/contrast-report.json';
const NEGATIVE_RULES = 'docs/specs/negative-rules.md';
const CONTRIBUTING = 'packages/react/CONTRIBUTING-COMPONENT.md';
const AUDITOR_TEMPLATE = '.claude/agents/ds-auditor.md';
const COMPONENTS_SRC = 'packages/react/src/components';

/**
 * Read every compiler input FRESH from disk (registries may be regenerated by
 * other pipeline stages between runs — never cache values into source).
 */
export function loadInputs(repoRoot: string, brand: string): CompilerInputs {
  const rawInputs = new Map<string, Buffer>();
  const read = (rel: string): Buffer => {
    const buf = readFileSync(join(repoRoot, rel));
    rawInputs.set(rel, buf);
    return buf;
  };

  const warnings: string[] = [];

  const tokensIndex = JSON.parse(read(REG_TOKENS).toString('utf8')) as TokensIndex;
  const componentsIndex = JSON.parse(read(REG_COMPONENTS).toString('utf8')) as ComponentsIndex;
  const contrastReport = JSON.parse(read(REG_CONTRAST).toString('utf8')) as ContrastReport;

  const brandPath = `brands/${brand}.json`;
  read(brandPath); // hashed as an input; resolved values come from the registry

  if (tokensIndex.brand !== brandPath) {
    warnings.push(
      `tokens-index.json was built against "${tokensIndex.brand}" but --brand resolves to "${brandPath}". ` +
        `Resolved token values reflect the registry's brand. The ingest pipeline must sequence ` +
        `tokens-build (--brand ${brand}) before context-build.`,
    );
  }
  if (contrastReport.brand !== tokensIndex.brand) {
    warnings.push(
      `contrast-report.json brand ("${contrastReport.brand}") does not match tokens-index.json brand ("${tokensIndex.brand}").`,
    );
  }
  if (tokensIndex.count !== tokensIndex.tokens.length) {
    warnings.push(
      `tokens-index.json declares count=${tokensIndex.count} but contains ${tokensIndex.tokens.length} tokens.`,
    );
  }

  const ruleCatalog = parseNegativeRules(read(NEGATIVE_RULES).toString('utf8'));
  const contributingMd = read(CONTRIBUTING).toString('utf8');
  const auditorTemplate = read(AUDITOR_TEMPLATE).toString('utf8');

  // Stories are contract artifacts (CLAUDE.md rule 8) — ground-truth usage.
  const storyFilesByExport = new Map<string, string[]>();
  const storyContents = new Map<string, string>();
  const dirs = readdirSync(join(repoRoot, COMPONENTS_SRC), { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();
  for (const dir of dirs) {
    const rel = `${COMPONENTS_SRC}/${dir}/${dir}.stories.tsx`;
    try {
      storyContents.set(rel, read(rel).toString('utf8'));
    } catch {
      warnings.push(`missing story file for component directory ${dir} (${rel})`);
    }
  }
  for (const comp of componentsIndex.components) {
    // A story exercises a component if it renders it as JSX (<Name …>) or
    // registers it as the CSF meta component (component: Name).
    const usage = new RegExp(`<${comp.name}[\\s/>]|component:\\s*${comp.name}\\b`);
    const files = [...storyContents.keys()].filter((p) => usage.test(storyContents.get(p) as string)).sort();
    storyFilesByExport.set(comp.name, files);
    if (files.length === 0) {
      warnings.push(`registry component ${comp.name} is not used in any story file (ground-truth gap)`);
    }
  }

  return {
    brand,
    tokensIndex,
    componentsIndex,
    contrastReport,
    ruleCatalog,
    contributingMd,
    auditorTemplate,
    storyFilesByExport,
    rawInputs,
    warnings,
  };
}
