import { COMPILER_PKG, CSS_PREFIX, REACT_PKG, estimateTokens } from './config.ts';
import type { ComponentEntry, CompilerInputs, NegativeRule, TokenEntry } from './types.ts';

/** Context shared by every emitter. */
export interface RenderCtx {
  inputs: CompilerInputs;
  sourceHash: string;
}

const REGEN = `pnpm --filter ${COMPILER_PKG} build`;

export function generatedLineMd(sourceHash: string): string {
  return `<!-- GENERATED by ${COMPILER_PKG} — DO NOT EDIT. Compiled from the machine registries and spec sources (source hash sha256:${sourceHash.slice(0, 16)}). Regenerate: ${REGEN} -->`;
}

export function generatedLineTxt(sourceHash: string): string {
  return `> GENERATED by ${COMPILER_PKG} — DO NOT EDIT. Source hash sha256:${sourceHash.slice(0, 16)}. Regenerate: ${REGEN}`;
}

export function generatedLineCss(sourceHash: string): string {
  return `# GENERATED by ${COMPILER_PKG} — DO NOT EDIT. Source hash sha256:${sourceHash.slice(0, 16)}.`;
}

export const CLOSED_WORLD =
  `This system is closed-world: every legal component is enumerated in ` +
  `registries/components-index.json and every legal token in registries/tokens-index.json. ` +
  `Anything not in those registries is provably fabricated — do not emit it.`;

/* ---------------------------------------------------------------- tables */

function cell(s: string): string {
  return s.replace(/\|/g, '\\|').replace(/\s*\n\s*/g, ' ').trim();
}

export function propsTable(comp: ComponentEntry): string {
  const rows = comp.props.map(
    (p) =>
      `| \`${cell(p.name)}\` | \`${cell(p.type)}\` | ${p.required ? 'yes' : 'no'} | ${
        p.defaultValue === null ? '—' : `\`${cell(p.defaultValue)}\``
      } | ${cell(p.description)} |`,
  );
  return [
    '| Prop | Type | Required | Default | Description |',
    '| --- | --- | --- | --- | --- |',
    ...rows,
  ].join('\n');
}

export function tokensTable(tokens: TokenEntry[]): string {
  const rows = tokens.map(
    (t) => `| \`${t.name}\` | \`${t.cssVar}\` | \`${cell(String(t.value))}\` | ${cell(t.description)} |`,
  );
  return ['| Token | CSS variable | Value | Description |', '| --- | --- | --- | --- |', ...rows].join('\n');
}

export function racBaseNote(comp: ComponentEntry): string {
  return comp.racBase === null
    ? `Static component (no react-aria-components base) — plain semantic HTML.`
    : `Built on react-aria-components \`${comp.racBase}\`; keyboard behavior, ARIA, and focus management ship inside. ` +
        `All \`${comp.racBase}\` base props (e.g. event handlers, \`isDisabled\`, \`autoFocus\`) are also legal here, ` +
        `with the props listed below overriding or narrowing them.`;
}

/* --------------------------------------------------------------- grouping */

export function semanticCategories(tokens: TokenEntry[]): Map<string, TokenEntry[]> {
  return groupBy(tokens.filter((t) => t.tier === 'semantic'));
}

export function componentTokenGroups(tokens: TokenEntry[]): Map<string, TokenEntry[]> {
  return groupBy(tokens.filter((t) => t.tier === 'component'));
}

function groupBy(tokens: TokenEntry[]): Map<string, TokenEntry[]> {
  const map = new Map<string, TokenEntry[]>();
  for (const t of tokens) {
    const cat = t.name.split('.')[0] as string;
    const list = map.get(cat) ?? [];
    list.push(t);
    map.set(cat, list);
  }
  const sorted = new Map<string, TokenEntry[]>();
  for (const key of [...map.keys()].sort()) {
    sorted.set(
      key,
      (map.get(key) as TokenEntry[]).slice().sort((a, b) => a.name.localeCompare(b.name)),
    );
  }
  return sorted;
}

export function sortedComponents(ctx: RenderCtx): ComponentEntry[] {
  return ctx.inputs.componentsIndex.components.slice().sort((a, b) => a.name.localeCompare(b.name));
}

/* ------------------------------------------------- shared rule rendering */

/** One negative rule as a compact wrong→right pair (single source for every channel). */
export function ruleCompact(r: NegativeRule): string {
  return [
    `### ${r.id} ${r.title}`,
    `- Wrong: ${r.wrong}`,
    `- Right: ${r.right}`,
    ...(r.why ? [`- Why: ${r.why}`] : []),
  ].join('\n');
}

export function rulesBlock(rules: NegativeRule[]): string {
  return rules.map(ruleCompact).join('\n\n');
}

/**
 * The core rule body shared verbatim by skills and every editor-rules channel
 * (Cursor / Copilot / Claude Code). Single source, multiple channels — the
 * channels must never drift (ADR-004).
 */
export function coreRuleBody(ctx: RenderCtx): string {
  const { ruleCatalog, tokensIndex, componentsIndex } = ctx.inputs;
  return [
    `> ${ruleCatalog.preamble}`,
    '',
    CLOSED_WORLD,
    '',
    '## Ground rules',
    '',
    `1. Import components ONLY from \`${REACT_PKG}\` — the single public entry point (${componentsIndex.components.length} exports, enumerated in registries/components-index.json).`,
    `2. Style ONLY with \`var(${CSS_PREFIX}-*)\` tokens (${tokensIndex.count} tokens, enumerated in registries/tokens-index.json). No hex, no px/rem literals, no utility classes.`,
    `3. Layout is plain elements + CSS with space tokens (\`display: flex; gap: var(${CSS_PREFIX}-space-gap-md)\`). There are no layout or typography components.`,
    `4. Semantic tokens by intent (\`${CSS_PREFIX}-color-surface-raised\`), never raw palette scales. Space tokens only in margin/padding/gap/inset; box dimensions use \`${CSS_PREFIX}-size-*\`.`,
    `5. Accessibility ships inside the components (react-aria-components). Never hand-roll focus management, and never bypass a component's ARIA wiring.`,
    `6. Before finishing, run the deterministic validation gauntlet (\`pnpm validate\`: typecheck → lint → build → test/a11y → registry check). It approves; no LLM does.`,
    '',
    '## Negative rules (observed hallucinations — wrong → right)',
    '',
    rulesBlock(ruleCatalog.rules),
  ].join('\n');
}

/* ----------------------------------------------------------------- misc */

export function fenced(code: string, lang: string): string {
  return `\`\`\`${lang}\n${code.trim()}\n\`\`\``;
}

export { estimateTokens, REGEN };
