import { COMPILER_PKG, CSS_PREFIX, REACT_PKG, estimateTokens } from './config.ts';
import type { ComponentEntry, CompilerInputs, NegativeRule, RacPropEntry, TokenEntry } from './types.ts';

/** Context shared by every emitter. */
export interface RenderCtx {
  inputs: CompilerInputs;
  sourceHash: string;
}

const REGEN = `pnpm --filter ${COMPILER_PKG} build`;

export function generatedLineMd(sourceHash: string): string {
  return `<!-- GENERATED by ${COMPILER_PKG} — DO NOT EDIT. Compiled from the machine registries and spec sources (source hash sha256:${sourceHash.slice(0, 16)}). Regenerate: ${REGEN} -->`;
}

export function generatedLineTxt(sourceHash: string): string {
  return `> GENERATED by ${COMPILER_PKG} — DO NOT EDIT. Source hash sha256:${sourceHash.slice(0, 16)}. Regenerate: ${REGEN}`;
}

export function generatedLineCss(sourceHash: string): string {
  return `# GENERATED by ${COMPILER_PKG} — DO NOT EDIT. Source hash sha256:${sourceHash.slice(0, 16)}.`;
}

export const CLOSED_WORLD =
  `This system is closed-world: every legal component is enumerated in ` +
  `registries/components-index.json and every legal token in registries/tokens-index.json. ` +
  `Anything not in those registries is provably fabricated — do not emit it.`;

/* ---------------------------------------------------------------- tables */

function cell(s: string): string {
  return s.replace(/\|/g, '\\|').replace(/\s*\n\s*/g, ' ').trim();
}

export function propsTable(comp: ComponentEntry): string {
  const rows = comp.props.map(
    (p) =>
      `| \`${cell(p.name)}\` | \`${cell(p.type)}\` | ${p.required ? 'yes' : 'no'} | ${
        p.defaultValue === null ? '—' : `\`${cell(p.defaultValue)}\``
      } | ${cell(p.description)} |`,
  );
  return [
    '| Prop | Type | Required | Default | Description |',
    '| --- | --- | --- | --- | --- |',
    ...rows,
  ].join('\n');
}

export function tokensTable(tokens: TokenEntry[]): string {
  const rows = tokens.map(
    (t) => `| \`${t.name}\` | \`${t.cssVar}\` | \`${cell(String(t.value))}\` | ${cell(t.description)} |`,
  );
  return ['| Token | CSS variable | Value | Description |', '| --- | --- | --- | --- |', ...rows].join('\n');
}

export function racBaseNote(comp: ComponentEntry): string {
  return comp.racBase === null
    ? `Static component (no react-aria-components base) — plain semantic HTML.`
    : `Built on react-aria-components \`${comp.racBase}\`; keyboard behavior, ARIA, and focus management ship inside. ` +
        `All \`${comp.racBase}\` base props (e.g. event handlers, \`isDisabled\`, \`autoFocus\`) are also legal here, ` +
        `with the props listed below overriding or narrowing them.`;
}

/** Normalize the OPTIONAL registry `racProps` enrichment (names or {name,type} objects). */
export function racProps(comp: ComponentEntry): RacPropEntry[] {
  return (comp.racProps ?? [])
    .map((p) =>
      typeof p === 'string' ? { name: p, type: null } : { name: p.name, type: p.type ?? null },
    )
    .filter((p) => typeof p.name === 'string' && p.name.length > 0)
    .sort((a, b) => a.name.localeCompare(b.name));
}

/** One-line inherited-props enumeration; null when the registry lacks racProps. */
export function racPropsLine(comp: ComponentEntry): string | null {
  const props = racProps(comp);
  if (props.length === 0) return null;
  const list = props.map((p) => (p.type === null ? `\`${p.name}\`` : `\`${p.name}: ${cell(p.type)}\``)).join(', ');
  const note = comp.racPropsNote !== undefined ? ` ${comp.racPropsNote.replace(/\s*\n\s*/g, ' ').trim()}` : '';
  return `Inherited-but-legal \`${comp.racBase ?? 'base'}\` props (from the registry \`racProps\` enumeration): ${list}.${note}`;
}

/** Component-tier theming-hook pointer; null when the registry lacks tokenPrefix (or it is null). */
export function tokenPrefixLine(comp: ComponentEntry): string | null {
  if (comp.tokenPrefix === undefined || comp.tokenPrefix === null) return null;
  return `Theming hooks: \`${CSS_PREFIX}-${comp.tokenPrefix}-*\` component-tier tokens (see registries/tokens-index.json); they belong to this component ONLY (NR-008).`;
}

/**
 * FB-7: Dialog renders and styles its own title from the required `title`
 * prop — heading guidance must not tempt agents into adding their own <h2>.
 */
export function dialogTitleNote(comp: ComponentEntry): string | null {
  if (comp.name !== 'Dialog') return null;
  return (
    `Dialog OWNS its title: the required \`title\` prop renders the dialog's accessible heading with the ` +
    `system's own typography — never add your own heading element (\`<h2>\`, etc.) to name the dialog. ` +
    `Headings inside the dialog body are for content sections only.`
  );
}

/* --------------------------------------------------------------- grouping */

export function semanticCategories(tokens: TokenEntry[]): Map<string, TokenEntry[]> {
  return groupBy(tokens.filter((t) => t.tier === 'semantic'));
}

export function componentTokenGroups(tokens: TokenEntry[]): Map<string, TokenEntry[]> {
  return groupBy(tokens.filter((t) => t.tier === 'component'));
}

function groupBy(tokens: TokenEntry[]): Map<string, TokenEntry[]> {
  const map = new Map<string, TokenEntry[]>();
  for (const t of tokens) {
    const cat = t.name.split('.')[0] as string;
    const list = map.get(cat) ?? [];
    list.push(t);
    map.set(cat, list);
  }
  const sorted = new Map<string, TokenEntry[]>();
  for (const key of [...map.keys()].sort()) {
    sorted.set(
      key,
      (map.get(key) as TokenEntry[]).slice().sort((a, b) => a.name.localeCompare(b.name)),
    );
  }
  return sorted;
}

export function sortedComponents(ctx: RenderCtx): ComponentEntry[] {
  return ctx.inputs.componentsIndex.components.slice().sort((a, b) => a.name.localeCompare(b.name));
}

/* ------------------------------------------------- shared rule rendering */

/** One negative rule as a compact wrong→right pair (single source for every channel). */
export function ruleCompact(r: NegativeRule): string {
  return [
    `### ${r.id} ${r.title}`,
    `- Wrong: ${r.wrong}`,
    `- Right: ${r.right}`,
    ...(r.why ? [`- Why: ${r.why}`] : []),
  ].join('\n');
}

export function rulesBlock(rules: NegativeRule[]): string {
  return rules.map(ruleCompact).join('\n\n');
}

/**
 * The core rule body shared verbatim by skills and every editor-rules channel
 * (Cursor / Copilot / Claude Code). Single source, multiple channels — the
 * channels must never drift (ADR-004).
 */
export function coreRuleBody(ctx: RenderCtx): string {
  const { ruleCatalog, tokensIndex, componentsIndex } = ctx.inputs;
  return [
    `> ${ruleCatalog.preamble}`,
    '',
    CLOSED_WORLD,
    '',
    '## Ground rules',
    '',
    `1. Import components ONLY from \`${REACT_PKG}\` — the single public entry point (${componentsIndex.components.length} exports, enumerated in registries/components-index.json).`,
    `2. Style ONLY with \`var(${CSS_PREFIX}-*)\` tokens (${tokensIndex.count} tokens, enumerated in registries/tokens-index.json). No hex, no px/rem literals, no utility classes.`,
    `3. Layout is plain elements + CSS with space tokens (\`display: flex; gap: var(${CSS_PREFIX}-space-gap-md)\`). There are no layout or typography components.`,
    `4. Semantic tokens by intent (\`${CSS_PREFIX}-color-surface-raised\`), never raw palette scales. Space tokens only in margin/padding/gap/inset; box dimensions use \`${CSS_PREFIX}-size-*\`.`,
    `5. Accessibility ships inside the components (react-aria-components). Never hand-roll focus management, and never bypass a component's ARIA wiring.`,
    `6. Before finishing, run the deterministic validation gauntlet (\`pnpm validate\`: typecheck → lint → build → test/a11y → registry check). It approves; no LLM does.`,
    '',
    '## Negative rules (observed hallucinations — wrong → right)',
    '',
    rulesBlock(ruleCatalog.rules),
  ].join('\n');
}

/**
 * FB-6: gap-trio vs plain space steps — the one-line preference, shared by
 * the theming slice and the use-system token reference (single source).
 */
export const GAP_VS_SPACE =
  `Gap vs space steps: the \`${CSS_PREFIX}-space-gap-{sm,md,lg}\` trio (tops out at \`gap-lg\`) is for intra-component rhythm ` +
  `(icon-to-label, control clusters, sibling gaps); larger section- and region-level separation uses the plain space steps ` +
  `(\`${CSS_PREFIX}-space-5\` and up).`;

/* ----------------------------------------------------------------- misc */

export function fenced(code: string, lang: string): string {
  return `\`\`\`${lang}\n${code.trim()}\n\`\`\``;
}

export { estimateTokens, REGEN };
