/**
 * Human report (intake-report.md) and machine publish plan (publish-plan.json)
 * emitters for a customer build. These two files are the delivery engineer's
 * hand-off: what was generated, every AA adjustment, what fell back to
 * defaults, what is still missing, and how (not yet automated) publishing works.
 */

import type { AaFixResult } from "./aa.js";
import type { Intake, PaletteFamily } from "./intake.js";
import type { GenerateResult } from "./brand.js";

export interface TokensBuildSummary {
  semanticCount: number;
  componentCount: number;
  contrastPairs: number;
  contrastFailures: number;
}

export interface PipelineReportData {
  intake: Intake;
  generate: GenerateResult;
  brandRelPath: string;
  outRelDir: string;
  tokensBuild: TokensBuildSummary;
  contextStatus: "built" | "skipped-absent" | "skipped-noncanonical-brand-path";
  emittedFiles: string[];
  registriesBefore: Record<string, string>;
  registriesAfter: Record<string, string>;
  timingsMs: Record<string, number>;
  warnings: string[];
}

function aaSection(aa: AaFixResult): string[] {
  const lines: string[] = [];
  lines.push(`Checked **${aa.pairs.length} mandated pairs** at threshold **${aa.threshold}:1** (WCAG 2.2 AA, normal text) — the exact pair list and contrast math the \`@ds/tokens\` build gate enforces. Final state: **0 failures**.`);
  lines.push("");
  if (aa.adjustments.length === 0) {
    lines.push("No adjustments were needed — every generated ramp cleared AA as generated.");
    return lines;
  }
  lines.push(`**${aa.adjustments.length} automatic adjustment(s)** (deterministic minimal darkening, same approach used by hand for the neutral core brand):`);
  lines.push("");
  lines.push("| Ramp step | Reason | Forcing pair | Before | After | Ratio before → after |");
  lines.push("|---|---|---|---|---|---|");
  for (const adj of aa.adjustments) {
    const pair = adj.pair ? `${adj.pair.foreground} on ${adj.pair.background}` : "—";
    const ratios =
      adj.ratioBefore !== undefined && adj.ratioAfter !== undefined
        ? `${adj.ratioBefore}:1 → ${adj.ratioAfter}:1`
        : "—";
    lines.push(`| \`${adj.rampPath}\` | ${adj.reason} | ${pair} | \`${adj.before}\` | \`${adj.after}\` | ${ratios} |`);
  }
  return lines;
}

export function renderIntakeReport(data: PipelineReportData): string {
  const { intake, generate } = data;
  const display = intake.displayName ?? intake.name;
  const lines: string[] = [];

  lines.push(`# Intake report — ${display} (\`${intake.name}\`)`);
  lines.push("");
  lines.push(`Generated by \`@ds/ingest\` (\`ds-ingest run\`). Brand file: \`${data.brandRelPath}\`. Output bundle: \`${data.outRelDir}/\`.`);
  lines.push("");

  lines.push("## Palette");
  lines.push("");
  lines.push("| Family | Source | Seed |");
  lines.push("|---|---|---|");
  for (const family of Object.keys(generate.rampSources) as PaletteFamily[]) {
    const src = generate.rampSources[family];
    lines.push(`| ${family} | ${src.source} | ${src.seed ? `\`${src.seed}\`` : "—"} |`);
  }
  lines.push("");
  lines.push("Ramp generation is deterministic: OKLCH lightness ladder (fixed per-step lightness targets; seed contributes hue + chroma only). Re-running the intake reproduces byte-identical ramps.");
  lines.push("");

  lines.push("## WCAG AA pre-check");
  lines.push("");
  lines.push(...aaSection(generate.aa));
  lines.push("");

  lines.push("## Defaults applied (intake was silent)");
  lines.push("");
  if (generate.defaultsUsed.length === 0) lines.push("None — the intake specified every field.");
  else for (const d of generate.defaultsUsed) lines.push(`- ${d}`);
  lines.push("");

  lines.push("## Tokens build (isolated)");
  lines.push("");
  lines.push(`- Semantic tokens: ${data.tokensBuild.semanticCount}`);
  lines.push(`- Component tokens: ${data.tokensBuild.componentCount}`);
  lines.push(`- Gate contrast pairs: ${data.tokensBuild.contrastPairs} checked, ${data.tokensBuild.contrastFailures} failures`);
  const contextLine =
    data.contextStatus === "built"
      ? "built with --brand into context/ (registry swap + byte-for-byte restore around the compile)"
      : data.contextStatus === "skipped-absent"
        ? "SKIPPED — @ds/context package not present in the workspace yet; re-run `ds-ingest run` once it lands"
        : "SKIPPED — brand file was written outside brands/ (--brand-out), where @ds/context resolves it";
  lines.push(`- Context artifacts: ${contextLine}`);
  lines.push("");

  lines.push("## Workspace isolation verification");
  lines.push("");
  lines.push("The tokens build ran with isolated `distDir`/`registriesDir` options; the workspace's default-brand `registries/` were hash-verified untouched:");
  lines.push("");
  lines.push("| File | SHA-256 before | SHA-256 after | Unchanged |");
  lines.push("|---|---|---|---|");
  for (const file of Object.keys(data.registriesBefore).sort()) {
    const before = data.registriesBefore[file] as string;
    const after = data.registriesAfter[file] ?? "(missing)";
    lines.push(`| ${file} | \`${before.slice(0, 16)}…\` | \`${after === before ? before.slice(0, 16) : after.slice(0, 16)}…\` | ${after === before ? "yes" : "NO"} |`);
  }
  lines.push("");

  lines.push("## Emitted files");
  lines.push("");
  for (const f of data.emittedFiles) lines.push(`- \`${f}\``);
  lines.push("");

  lines.push("## Timings");
  lines.push("");
  for (const [phase, ms] of Object.entries(data.timingsMs)) lines.push(`- ${phase}: ${ms} ms`);
  lines.push("");

  lines.push("## Gaps / follow-ups");
  lines.push("");
  const gaps: string[] = [...data.warnings];
  if (intake.assets) {
    gaps.push("Logo asset paths are recorded in the brand file but assets are not copied/processed yet (no asset pipeline in Phase 4).");
  } else {
    gaps.push("No logo assets supplied at intake.");
  }
  gaps.push("npm publish is documented in publish-plan.json but intentionally NOT executed by the pipeline.");
  gaps.push("Semantic override layer (allowlisted extension points, ADR-006 §4) is out of ingest scope — standard engagement assumed.");
  for (const g of gaps) lines.push(`- ${g}`);
  lines.push("");

  return `${lines.join("\n")}`;
}

export function renderPublishPlan(data: PipelineReportData): Record<string, unknown> {
  const { intake } = data;
  const scope = intake.distribution.npmScope;
  const access = intake.distribution.publicDocs ? "public" : "restricted";
  return {
    $description:
      "GENERATED publish plan. Documents how this customer bundle ships to npm. The publish step is deliberately NOT automated by ds-ingest (Phase 4); a release engineer executes publishSteps after review.",
    customer: intake.name,
    displayName: intake.displayName ?? intake.name,
    npmScope: scope,
    access,
    publicDocs: intake.distribution.publicDocs,
    packages: [
      {
        name: `${scope}/tokens`,
        description: "Compiled design tokens for this brand: CSS custom properties, TS literal-union types, closed-world registries.",
        files: {
          "css/tokens.css": "tokens/css/tokens.css",
          "index.js": "tokens/index.js",
          "index.d.ts": "tokens/index.d.ts",
          "registries/tokens-index.json": "registries/tokens-index.json",
          "registries/contrast-report.json": "registries/contrast-report.json",
          "brand.json": "brand.json",
          "intake-report.md": "intake-report.md",
        },
      },
      {
        name: `${scope}/context`,
        description: "Per-customer AI consumption layer (llms.txt family, skills, AGENTS.md, editor rules) re-emitted with this brand's values.",
        status: data.contextStatus === "built" ? "ready" : "pending — @ds/context not built for this brand yet",
        files: data.contextStatus === "built" ? { "context/": "context/" } : {},
      },
    ],
    publishSteps: [
      `1. Review intake-report.md with the customer (AA adjustments are contract-visible changes to their palette).`,
      `2. Create/verify the private scope ${scope} on the registry; access level: ${access} (ADR-006: gated by default${intake.distribution.publicDocs ? " — this customer explicitly opted into public docs" : ""}).`,
      `3. Stage a package.json per package above (name, version from the engagement tag, files map) alongside the listed artifacts.`,
      `4. npm publish --access ${access} from each staged package directory (CI job, provenance on).`,
      `5. Record the published versions in the engagement log; registries/ stay the customer's closed-world contract.`,
    ],
    automated: false,
  };
}
